### PR TITLE
Refactor + Exposing generated ParseTree

### PR DESCRIPTION
**Pull request by tylermmorton**
Hi @gotnospirit! Hope you are well!

I've been working with your library for the past few weeks and I've had to refactor it a bit to support some features for a localization library I'm building:
- Split the parsing and formatting into two separate interfaces. The API now looks like `messageformat.NewParser()` and `messageformat.NewFormatter()` -- This was done to allow for better test mocking
- All parse* and format* functions are now methods on the Parser and Formatter types respectively. 
- Linted the project with `staticheck` and removed yoda expressions 
- Created a basic `Expression` type for each of the parsed ICU nodes. Also planning to store positional data as a part of these expressions as well. 
- Renamed the data structure generated by the parser to `ParseTree`
  - You can traverse the `ParseTree` using the `ForEach` method, which exposes access to the children nodes for things like linting.
- Added `json` struct tags to each node in the `ParseTree` to allow for marshaling. Currently unmarshaling is unimplemented due to how Go handles encoding/decoding nested structs in json. Gotta keep playing with this.

I recognize these changes are not backwards compatible and probably call for a v2 so I understand if you have no interest in merging this PR. I'll probably continue to maintain a fork in that case.

Let me know what you think!

- Tyler

### CODE REVIEW

**Comment by gotnospirit** [comment]
Hi!

Besides things related to `staticcheck`, I mostly disagree with the rest of the changes made here.
I think they are introduced for purposes that are not directly related with the module itself.

While I don't really mind about having things like `NewParser` & `NewFormatter` in itself, this hits usability
https://github.com/tylermmorton/messageformat/blob/4b5feef2eed60085d01becdefbbbe3d57c02bb37/parser_test.go#L21-L28

and the greatest problem I see, is that the module can't be extended anymore (by using `Register` method).
While this introduce drawbacks like unused arguments for format functions, I think it's important to keep this functionality.
https://github.com/gotnospirit/messageformat/blob/89e2ff081b8b1ea1ea38a6f604bce04b143b05e2/literal.go#L7

I agree that the design isn't perfect (at all), and we can talk about changing things, but the main purpose is to be easy to use:
- Get a default configured instance (culture, defaults parse/format functions, ...)
- Use that instance to parse "MessageFormat" string and return another instance (maybe a Formatter as in your PR)
- Use that "formatter" to apply data and get the final reduced string

The parse and formatting are separated steps because parsing the same string everytime we just change the data (e.g. in a webservice context) would be a waste of computing, but they are tightly coupled because the only purpose is giving a MessageFormat input and get a "correctly reduced" output (based on data).

`root` (which is a `node`) and `node.children` are private props of the module because if the tree ("root") is changed after parsing, then the reduced string won't have relations with the input string. We can discuss about a way to retrieve a tree from the parsing step, but mutate this tree should not have effect on the formatting (in short retrieve a copy of the tree).

If you need the "positional data" for some purpose, we can discuss about a way to get them (I don't know maybe a kind of "callback system" during parsing) but these data don't belong to the parsed expressions (expression's purpose is to be reduced in formatting step)
Adding the JSON things, I definitely think you need a way to hook in parsing, because (un)marshalling related things should be external to the module (it doesn't serve its purpose)

`ColonChar` wasn't defined in Parser because it's specific to "parsePlural"

Regarding `staticcheck`:
- ST1017: I agree that, while "yoda conditions" are a sanity-saver for devs with other languages, they can be removed here
- S1034: I agree
- ST1005: I rather don't agree because it's composability problem, if not needed, then there's missing capital letters
- SA4006: True, I think `err` should be ignored here, because if I remember well, it was hard to find an input that would break at this line
- SA4009: True, I think this `char` argument is useless

After reading my code (to compare with the whole PR), If I had to change something now, I would:
- remove `MessageFormat.SetCulture` & `MessageFormat.SetPluralFunction`, because the plural function is related to the culture, and changing the culture after parsing makes no sense from a usage point of view
- remove `Parser.New`, and rename `Parser.NewWithCulture` into `Parser.New`, because `make_plural` module may be generated without "en" support
(Edit: This 2 remarks are for me, not to be done ^^)

**Comment by tylermmorton** [comment]
I think it would help if I explained the problems I was trying to solve and some additional context around the changes I'm proposing. I'm definitely willing to continue iterating on these changes and work together to improve the library.

For context, I'm currently building a localization toolchain for web services that uses ICU as the underlying message formatting solution. The first iteration of the tooling included a `Localizer` that would load strings from a JSON file, parse them into `MessageFormat` objects and store them to be formatted later. 

It became apparent that errors around parsing and formatting within the localization library needed to be "factored out" in order to increase stability, performance and API ergonomics. For this, I decided that static analysis tooling for the ICU strings was the best approach. Being able to parse and check the structure of ICU messages at build time removes the need to do it at runtime.

There were also additional ideas surfacing around combining ICU ParseTree analysis with Go AST analysis, in order to lint calls to `FormatMap` and ensure the given map keys line up with the keys of the ICU string. This is something that Format.js does really well.

Finally, in an effort to reduce web service initialization time, instead of storing messages as strings in a JSON file and parsing them when a web service starts up, the idea of marshaling/unmarshaling the ParseTree directly was proposed. I still haven't been able to do this part successfully yet, and more benchmark testing needs to be done to prove this hypothesis.

During all of this I realized that the nodes of the parsed string were not exposed so it was not possible to build any of these static analysis tools on top of the messageformat library, which is what inspired this set of changes. 

> I think they are introduced for purposes that are not directly related with the module itself.

I agree, I built these changes around the use cases that I described. I recognize I was liberal with design changes around internals that could be walked back, but I stand by the idea that exposing the ParseTree is an important feature that messageformat needs. I'd like to continue iterating on this and get to a place where this can be a valuable contribution to the library.

**Comment by gotnospirit** [comment]
I'm not against the ideas but the basic usage (as explained earlier) must be preserved.

I'm not familiar with `go/ast` but it seems possible to implement a subset of their types and being able to use `ast.Inspect`.
We could have something like
```
o, err := New("en")
node, err := o.ParseTree(input)
ast.Inspect(node, func(n ast.Node) bool {
...
})
```

Overall, the changes must be done step-by-step and clearly identified (different commits/pull requests), instead of a big block.

As an example, in this PR, some error messages were rewritten, but if a user already do some kind of parsing for errors then it will be broken. He check in the history where it comes from and why, and won't understand the reason.
I think doing breaking changes is also a good occasion to introduce well defined typed errors.

I propose to first create a `2.x` branch where these kind of changes could be done safely, and later when everything is finished and ok, move `master` into a `1.2` branch.

What do you think about it?

**Comment by gotnospirit** [comment]
Also, more attention in introducing rather new go sugar (e.g. `any` or generics) should be considerated more consciously and being discussed, because it's not easy for everyone to upgrade production servers

**Pull request closed without merging**
